# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

default:
  # default to tag to get scheduled on 'bignlp' runners
  tags:
    - gitlab-runner-bignlp-api
  # sane default, every job can be cancelled by some other event (override in jobs that can't be interrupted; i.e. deployment)
  interruptible: true

workflow:
  rules:
    # no branch pipeline while MR is open against same branch
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # tag pipelines allowed
    - if: $CI_COMMIT_TAG
    # protected branch and tag pipelines allowed
    - if: $CI_COMMIT_REF_PROTECTED
    # schedule pipelines allowed
    - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - lint
  - test
  - build
  - publish
  - security

include:
  - project: dl/ai-services/gitlab-templates
    ref: main
    file:
      - /templates/docker-utils.gitlab-ci.yml
      #- /templates/ephemeral-utils.gitlab-ci.yml
      - /templates/helm-utils.gitlab-ci.yml
  - component: gitlab-master.nvidia.com/dl/ai-services/gitlab-components/nemo-util/vault-init@1.0
  - component: gitlab-master.nvidia.com/dl/ai-services/gitlab-components/nemo-pipeline/security@0.2.0
    inputs:
      container_image: ${CI_REGISTRY_IMAGE}/${SERVICE_NAME}:${CI_COMMIT_SHA}
      nspect_id: NSPECT-4DWD-VFPM

# common variables for the pipeline
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  GIT_SUBMODULE_DEPTH: 1
  MORPHEUS_BASE_IMG: nvcr.io/nvidia/morpheus/morpheus
  MORPHEUS_TAG: v24.03.02-runtime
  POETRY_VERSION: 1.7.1
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
  SERVICE_NAME: nv-ingest
  NGC_REGISTRY: nvcr.io
  HELM_REPO: https://helm.ngc.nvidia.com/nvidian/nemo-llm
  HELM_REPO_NAME: ngc
  HELM_API_TOKEN: $NGC_REGISTRY_PASSWORD

.nemo-pipeline-scripts:
  iac-scan-matrix:
    matrix:
      - TARGET_CONFIG_PATH:
          - Dockerfile
          - helm/

##################
###   PYTHON   ###
##################
.python-basics:
  image: $MORPHEUS_BASE_IMG:$MORPHEUS_TAG
  # DAG approach, does not wait for previous state to finish
  needs: [ ]
  # cache for python packages, unique for each branch (not shared across branches)
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/poetry
      - .venv/
  before_script:
    - apt-get update
    - apt-get install --no-install-recommends --yes git-core gcc libgl1-mesa-glx
    # TODO this should just be in the image already instead of downloading every time, same with git-core
    - pip install .
    - pip install ./client

lint:
  extends: .python-basics
  stage: lint
  script:
    - pip install -r test-requirements.txt
    - DISABLE_FIX_IN_PLACE=1 ./ci/scripts/fix_all.sh

test:
  extends: .python-basics
  stage: test
  tags:
    - h100

  script:
    - pip install -r test-requirements.txt
    - pytest -rs --cov nv_ingest --cov nv_ingest_client --cov-report term --cov-report xml:coverage.xml tests/nv_ingest tests/nv_ingest_client
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

##################
###   DOCKER   ###
##################
build_and_publish:docker:
  stage: build
  extends: .docker-kaniko-build
  dependencies:
    - build:pip_packages
  needs:
    - job: build:pip_packages
      artifacts: true
  script:
    - ls -lah ./
    - ls -lah ./ci/scripts
    - chmod +x ./ci/scripts/build_and_publish_container.sh
    - if [[ "$CI_PIPELINE_SOURCE" == "schedule" && "$SCHEDULE_NAME" == "publish-nightly" ]]; then sh ./ci/scripts/build_and_publish_container.sh --type dev; fi
    - if [[ "$CI_PIPELINE_SOURCE" == "web" && "$CI_JOB_NAME" == "publish-release" ]]; then sh ./ci/scripts/build_and_publish_container.sh --type release; fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "publish-nightly"'
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_JOB_NAME == "publish-release"'

######################
### PACKAGE BUILDS ###
######################
build:pip_packages:
  extends: .python-basics
  stage: build
  script:
    - chmod +x ./ci/scripts/build_pip_packages.sh
    - if [[ "$CI_PIPELINE_SOURCE" == "schedule" && "$SCHEDULE_NAME" == "publish-nightly" ]]; then ./ci/scripts/build_pip_packages.sh --type dev --lib client; ./ci/scripts/build_pip_packages.sh --type dev --lib service; fi
    - if [[ "$CI_PIPELINE_SOURCE" == "web" && "$CI_JOB_NAME" == "publish-release" ]]; then ./ci/scripts/build_pip_packages.sh --type release --lib client; ./ci/scripts/build_pip_packages.sh --type release --lib service; fi
  artifacts:
    paths:
      - client/dist/*.whl
      - dist/*.whl
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "publish-nightly"'
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_JOB_NAME == "publish-release"'


##################
### PUBLISHING ###
##################

publish:pip_packages:
  image: python:3.11
  stage: publish
  script:
    # Debugging step to verify artifacts
    - echo "Listing artifacts in client/dist/ and dist/"
    - ls -la client/dist/
    - ls -la dist/
    # Install Twine for uploading packages
    - pip install twine
    # Ensure the publish script is executable and run it
    - chmod +x ./ci/scripts/publish_pip_packages.sh
    - ./ci/scripts/publish_pip_packages.sh --use-gitlab
  dependencies:
    - build:pip_packages
  needs:
    - job: build:pip_packages
      artifacts: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "publish-nightly"'
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_JOB_NAME == "publish-release"'


##################
### HELM CHART ###
##################

# lint the chart for basic errors
lint:helm:
  stage: test
  extends: .helm-lint

# version check helm charts if there are changes only
check:helm:
  stage: test
  extends: .helm-publish-check
  needs:
    - job: lint:helm
      optional: true
    - job: vault-init
      optional: false

# publish helm charts only if there are changes
publish:helm:
  stage: publish
  extends: .helm-publish
  needs:
    - job: check:helm
      optional: true
    - job: vault-init
      optional: true
  script:
    - helm cm-push -f "${CHART}" "${HELM_REPO_NAME}"


##################
###   PUBLISH  ###
##################

# Take snapshot SHA and publish to NGC
#nvcr-sha:
#  stage: publish
#  extends: .sha-release
#  needs: [vault-init, build:docker]
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      when: on_success
#    - when: manual
#      allow_failure: true
#  variables:
#    REMOTE_IMAGE_URI: ${NGC_REGISTRY}/nvidian/nemo-llm/${SERVICE_NAME}
#
## publish image tag to NGC
#nvcr-tag:
#  stage: publish
#  extends: .tag-release
#  needs: [vault-init, build:docker]
