# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: "(^src/vendor/|client/python)"
  #- repo: https://github.com/PyCQA/flake8
  #  rev: 6.1.0
  #  hooks:
  #    - id: flake8
  #      exclude: "^src/vendor/"
  #      additional_dependencies: ["flake8-print"]
  #      args: ["--exclude=client/python/*", "--ignore=E203"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
  #- repo: local
  #  hooks:
  #    - id: mypy
  #      name: mypy
  #      language: system
  #      entry: poetry
  #      args: ["run", "mypy"]
  #      files: "^(?!src/vendor/)(src|tests)/.*"
  #      types: [python]
  #      exclude: "^client/python"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown]
        exclude: "^(src/vendor/|openapi/.*openapi.*.yaml|client/python)"
