services:
  morpheus-ms-base:
    image: "morpheus-ms-base:24.03"
    build:
      context: ${MORPHEUS_ROOT}
      dockerfile: "./docker/Dockerfile"
      target: runtime
      network: host
      args:
        CUDA_MAJOR_VER: 12
        CUDA_MINOR_VER: 1
        CUDA_REV_VER: 1
        DOCA_ARTIFACTS_HOST:
        DOCA_REPO_HOST:
        FROM_IMAGE: nvidia/cuda
        LINUX_DISTRO: ubuntu
        LINUX_VER: "22.04"
        MORPHEUS_ROOT_HOST: .
        MORPHEUS_SUPPORT_DOCA: OFF
        PYTHON_VER: "3.10"
    volumes:
      - ${MORPHEUS_PDF_INGEST_ROOT}/models:/models
    command: >
      bash -c "python -m pip install sentence_transformers onnx && python /workspace/examples/llm/main.py vdb_upload export-triton-model --model_name ${MODEL_NAME} --triton_repo /models/triton-model-repo"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"

  tika:
    image: apache/tika:latest
    ports:
      - "9998:9998"

  triton:
    image: "nvcr.io/nvidia/tritonserver:23.12-py3"
    command: >
      bash -c "tritonserver --model-repository=/models/triton-model-repo --exit-on-error=false --model-control-mode=explicit --load-model ${MODEL_NAME}"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ${MORPHEUS_PDF_INGEST_ROOT}/models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  nv-ingest-ms-runtime:
    image: "nv-ingest-ms-runtime:24.03"
    build:
      context: ${MORPHEUS_PDF_INGEST_ROOT}
      dockerfile: "./Dockerfile"
      target: runtime
    volumes:
      - ${DATASET_ROOT}:/workspace/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_MORPHEUS_TASK_QUEUE=morpheus_task_queue
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  nv-ingest-ms-dev:
    image: "nv-ingest-ms-dev:24.03"
    build:
      context: ${MORPHEUS_PDF_INGEST_ROOT}
      dockerfile: "./Dockerfile"
      target: development
    volumes:
      - ${DATASET_ROOT}:/workspace/data
      - ${MORPHEUS_PDF_INGEST_ROOT}/src:/workspace/src
    stdin_open: true
    tty: true      
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_MORPHEUS_TASK_QUEUE=morpheus_task_queue
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]              
