# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

services:
  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"

    build:
      context: ${NV_INGEST_ROOT:-.}
      dockerfile: "./Dockerfile"
      target: development
    volumes:
      - ${NV_INGEST_ROOT}:/workspace/nv_ingest_dev
    environment:
      # Bump logging for dev work
      - INGEST_LOG_LEVEL=DEBUG

      # build.nvidia.com hosted cached endpoints.
      - CACHED_HTTP_ENDPOINT=https://ai.api.nvidia.com/v1/cv/university-at-buffalo/cached
      - CACHED_INFER_PROTOCOL=http

      # build.nvidia.com hosted deplot
      - DEPLOT_HTTP_ENDPOINT=https://ai.api.nvidia.com/v1/vlm/google/deplot
      - DEPLOT_INFER_PROTOCOL=http

      # build.nvidia.com hosted paddle endpoints.
      - PADDLE_HTTP_ENDPOINT=https://ai.api.nvidia.com/v1/cv/baidu/paddleocr
      - PADDLE_INFER_PROTOCOL=http

      # build.nvidia.com hosted yolox endpoints.
      - YOLOX_HTTP_ENDPOINT=https://ai.api.nvidia.com/v1/cv/nvidia/nv-yolox-page-elements-v1
      - YOLOX_INFER_PROTOCOL=http
