# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

services:

  nv-ingest-ms-runtime:
    ports:
      # Simple Broker
      - "7671:7671"
    environment:
      # Message client for development
      - MESSAGE_CLIENT_HOST=0.0.0.0
      - MESSAGE_CLIENT_PORT=7671
      - MESSAGE_CLIENT_TYPE=simple # Configure the ingest service to use the simple broker
