apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nv-ingest-poc-admin-role
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
