---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nv-ingest.fullname" . }}
  labels:
    {{- include "nv-ingest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      {{- with .Values.service.nodePort }}
      nodePort:  {{ . }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "nv-ingest.selectorLabels" . | nindent 4 }}
