name: nv_ingest_common
channels:
  - nvidia/label/dev
  - rapidsai
  - nvidia
  - conda-forge
  - pytorch
dependencies:
  - azure-core>=1.32.0
  - click>=8.1.7
  - fastparquet>=2024.11.0
  - fsspec>=2024.10.0
  - openai>=1.57.1
  - pydantic>2.0.0
  - pydantic-settings>2.0.0
  - pypdfium2>=4.30.0
  - pytest>=8.0.2
  - pytest-mock>=3.14.0
  - pytest-cov>=6.0.0
  - python>=3.10
  - python-docx>=1.1.2
  - python-dotenv>=1.0.1
  - python-pptx>=1.0.2
  - requests>=2.32.3
  - setuptools>=58.2.0
  - pip
  - pip:
      - opencv-python # For some reason conda cant solve our req set with py-opencv so we need to use pip
