FROM nvcr.io/nvidia/pytorch:24.06-py3

# INSTALL YOLOX
RUN git clone https://github.com/Megvii-BaseDetection/YOLOX.git && \
    cd YOLOX && \
    pip3 install -v -e . && cd .. && \
    pip3 uninstall opencv -y
