#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate unified configuration reference documentation for MkDocs."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs" / "docs" / "reference"

GENERATED_BANNER = "<!-- Generated by docs/scripts/generate_config_docs.py; do not edit by hand. -->\n\n"


def _ensure_imports() -> None:
    src = REPO_ROOT / "nemo_retriever" / "src"
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))


def _field_table(model: type[BaseModel], *, prefix: str = "") -> list[str]:
    from nemo_retriever.config.justification import field_justification_metadata

    lines = [
        "| Field | Type | Default | Description | Impact |",
        "|-------|------|---------|-------------|--------|",
    ]
    for name, field in model.model_fields.items():
        annotation = getattr(field.annotation, "__name__", str(field.annotation))
        default = field.get_default()
        default_repr = "`None`" if default is None else f"`{default!r}`"
        description = (field.description or "").replace("|", "\\|").replace("\n", " ")
        tags, rationale = field_justification_metadata(field)
        impact = ", ".join(tag.value.upper() for tag in tags)
        if rationale and not description:
            description = rationale.replace("|", "\\|")
        elif rationale:
            description = f"{description} — {rationale}".replace("|", "\\|")
        path = f"{prefix}.{name}" if prefix else name
        lines.append(f"| `{path}` | `{annotation}` | {default_repr} | {description or '—'} | {impact or '—'} |")
    return lines


def _model_section(title: str, model: type[BaseModel], *, prefix: str = "") -> str:
    doc = (model.__doc__ or "").strip()
    body = [f"### {title}", ""]
    if doc:
        body.extend([doc, ""])
    body.extend(_field_table(model, prefix=prefix))
    body.append("")
    return "\n".join(body)


def generate_overview() -> str:
    return (
        GENERATED_BANNER
        + """# Configuration reference

NeMo Retriever uses a single YAML file (`retriever-config.yaml` or `retriever-service.yaml`) backed by
`RetrieverServiceConfig`. Service topology sections configure deployment; `pipeline_defaults` holds SDK
stage params (`ExtractParams`, `EmbedParams`, …) shared across inprocess, batch, and service modes.

## Discovery precedence

1. Explicit `--config /path/to/file.yaml`
2. `./retriever-config.yaml` then `./retriever-service.yaml` in the working directory
3. Bundled defaults shipped with the package

Call-site kwargs and per-request `PipelineSpec` overrides always win over YAML defaults.

## Local vs remote NIM

When both a NIM endpoint URL and in-pod Hugging Face models are configured for a stage, **the NIM URL wins**.
Local models apply only for stages without a matching remote endpoint.

## SDK introspection

```python
from nemo_retriever import get_config, print_config, list_configured, save_config

print_config()
for entry in list_configured():
    print(entry.section, entry.justification, entry.rationale)
```

## Impact tag legend

| Tag | Meaning |
|-----|---------|
| `PERFORMANCE` | Overall runtime efficiency |
| `ACCURACY` | Output quality / correctness |
| `THROUGHPUT` | Documents or pages per unit time |
| `LATENCY` | Per-request / per-page wall time |
| `MEMORY` | RAM / VRAM footprint |
| `COST` | Cloud / NIM / token spend |
| `RELIABILITY` | Retries, timeouts, backpressure |
| `SECURITY` | Auth, secrets, allowlists |
| `COMPATIBILITY` | Model/API compatibility across run modes |
"""
    )


def generate_service_doc() -> str:
    from nemo_retriever.config.models import RetrieverServiceConfig
    from nemo_retriever.config.pipeline_defaults import PipelineDefaultsConfig
    from nemo_retriever.config.service_models import (
        AuthConfig,
        GatewayConfig,
        LLMConfig,
        LocalModelsConfig,
        LoggingConfig,
        MCPConfig,
        NimEndpointsConfig,
        PipelineOverridesConfig,
        PipelinePoolConfig,
        ResourceLimitsConfig,
        ServerConfig,
        VectorDbConfig,
        WorkQueueConfig,
    )

    sections: list[tuple[str, type[BaseModel], str]] = [
        ("server", ServerConfig, "server"),
        ("logging", LoggingConfig, "logging"),
        ("nim_endpoints", NimEndpointsConfig, "nim_endpoints"),
        ("local_models", LocalModelsConfig, "local_models"),
        ("llm", LLMConfig, "llm"),
        ("resources", ResourceLimitsConfig, "resources"),
        ("auth", AuthConfig, "auth"),
        ("mcp", MCPConfig, "mcp"),
        ("gateway", GatewayConfig, "gateway"),
        ("pipeline", PipelinePoolConfig, "pipeline"),
        ("work_queue", WorkQueueConfig, "work_queue"),
        ("vectordb", VectorDbConfig, "vectordb"),
        ("pipeline_overrides", PipelineOverridesConfig, "pipeline_overrides"),
        ("pipeline_defaults", PipelineDefaultsConfig, "pipeline_defaults"),
    ]

    parts = [
        GENERATED_BANNER,
        "# Service configuration sections",
        "",
        (RetrieverServiceConfig.__doc__ or "").strip(),
        "",
    ]
    for title, model, prefix in sections:
        parts.append(_model_section(title, model, prefix=prefix))
    return "\n".join(parts)


def generate_pipeline_defaults_doc() -> str:
    from nemo_retriever.config import list_configured
    from nemo_retriever.config.pipeline_defaults import PipelineDefaultsConfig
    from nemo_retriever.service.services import pipeline_executor  # noqa: F401 — register @configured

    _ = pipeline_executor
    parts = [
        GENERATED_BANNER,
        "# Pipeline defaults (`pipeline_defaults`)",
        "",
        (PipelineDefaultsConfig.__doc__ or "").strip(),
        "",
        _model_section("pipeline_defaults", PipelineDefaultsConfig, prefix="pipeline_defaults"),
        "## Configured resolvers",
        "",
        "| Function | Section | Variants | Impact | Rationale |",
        "|----------|---------|----------|--------|-----------|",
    ]
    for entry in list_configured():
        impacts = ", ".join(tag.value.upper() for tag in entry.justification)
        variants = ", ".join(entry.variants) or "—"
        rationale = (entry.rationale or "—").replace("|", "\\|")
        parts.append(f"| `{entry.qualname}` | `{entry.section}` | {variants} | {impacts or '—'} | {rationale} |")
    parts.append("")
    return "\n".join(parts)


def generate_by_impact_doc() -> str:
    from nemo_retriever.config import ConfigJustification, list_configured
    from nemo_retriever.service.services import pipeline_executor  # noqa: F401

    _ = pipeline_executor
    parts = [
        GENERATED_BANNER,
        "# Configuration by impact",
        "",
        "Index of `@configured` resolver sites grouped by impact tag.",
        "",
    ]
    for tag in ConfigJustification:
        entries = [e for e in list_configured() if tag in e.justification]
        parts.append(f"## {tag.name}")
        parts.append("")
        if not entries:
            parts.append("_No registered resolvers._")
            parts.append("")
            continue
        for entry in entries:
            parts.append(f"- **`{entry.section}`** — `{entry.qualname}`: {entry.rationale or '—'}")
        parts.append("")
    return "\n".join(parts)


OUTPUTS = {
    "configuration.md": generate_overview,
    "configuration-service.md": generate_service_doc,
    "configuration-pipeline-defaults.md": generate_pipeline_defaults_doc,
    "configuration-by-impact.md": generate_by_impact_doc,
}


def write_docs(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for filename, generator in OUTPUTS.items():
        path = output_dir / filename
        path.write_text(generator())


def check_docs(output_dir: Path) -> int:
    mismatches: list[str] = []
    for filename, generator in OUTPUTS.items():
        path = output_dir / filename
        expected = generator()
        if not path.is_file():
            mismatches.append(f"missing {path}")
            continue
        if path.read_text() != expected:
            mismatches.append(f"stale {path}")
    if mismatches:
        print("Configuration docs are out of date:", file=sys.stderr)
        for item in mismatches:
            print(f"  - {item}", file=sys.stderr)
        print("Run: python docs/scripts/generate_config_docs.py --write", file=sys.stderr)
        return 1
    print("Configuration docs are up to date.")
    return 0


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write generated markdown files")
    parser.add_argument("--check", action="store_true", help="Fail if generated files differ")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DOCS_DIR,
        help="Directory for generated markdown (default: docs/docs/reference)",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    _ensure_imports()

    if args.write:
        write_docs(args.output_dir)
        print(f"Wrote configuration docs to {args.output_dir}")
        return 0
    if args.check:
        return check_docs(args.output_dir)

    write_docs(args.output_dir)
    print(f"Wrote configuration docs to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
