apiVersion: v2
name: nv-ingest
description: NV-Ingest Microservice
type: application
version: 0.2.23
maintainers:
  - name: NVIDIA Corporation
    url: https://www.nvidia.com/
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 19.1.3
  - name: zipkin
    repository: https://zipkin.io/zipkin-helm
    version: 0.1.2
    condition: zipkinDeployed
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.78.1
    condition: otelDeployed
