affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80

# Redis configurations
redis:
  auth:
    enabled: false

# Kafka configutaions
kafkaEnabled: false

# Tika configurations
tikaEnabled: false

# Define environment variables as key/value dictionary pairs
envVars:
  MESSAGE_CLIENT_HOST: "nv-ingest-redis-master"
  MESSAGE_CLIENT_PORT: "6379"
  REDIS_MORPHEUS_TASK_QUEUE: "morpheus_task_queue"
  NV_INGEST_DEFAULT_TIMEOUT_MS: "1234"
  TABLE_DETECTION_GRPC_TRITON: nvingest-yolox:8001
  # The dependency for MINIO is missing
  MINIO_INTERNAL_ADDRESS: minio:9000
  MINIO_PUBLIC_ADDRESS: http://localhost:9000

logLevel: DEBUG

otelEnvVars:
  # OpenTelemetry
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://$(HOST_IP):4317" # sends to gRPC receiver on port 4317
  OTEL_SERVICE_NAME: "nemo-retrieval-service"
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: none
  OTEL_PROPAGATORS: "tracecontext,baggage"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=$(NAMESPACE)"
  OTEL_PYTHON_EXCLUDED_URLS: "health"

# ConfigMap containing extra env vars to load
extraEnvVarsCM: ""
# Secret containing extra sensitive env vars to load
extraEnvVarsSecret: ""
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: ""
  tag: ""

ingress:
  annotations: {}
  className: ""
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []

livenessProbe:
  httpGet:
    path: /health
    port: http
  periodSeconds: 10
  timeoutSeconds: 20
  failureThreshold: 20

startupProbe:
  httpGet:
    path: /health
    port: http
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 220

readinessProbe:
  httpGet:
    path: /health
    port: http

nameOverride: ""
nodeSelector: {}

otelEnabled: false
otelDeployed: false

opentelemetry-collector:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            cors:
              allowed_origins:
                - "*"
    exporters:
      # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
      zipkin:
        endpoint: "http://nv-ingest-ms-runtime-zipkin:9411/api/v2/spans"
      debug:
        verbosity: detailed
    extensions:
      health_check: {}
      zpages:
        endpoint: 0.0.0.0:55679
    processors:
      batch: {}
      tail_sampling:
        # filter out health checks
        # https://github.com/open-telemetry/opentelemetry-collector/issues/2310#issuecomment-1268157484
        policies:
          - name: drop_noisy_traces_url
            type: string_attribute
            string_attribute:
              key: http.target
              values:
                - \/health
              enabled_regex_matching: true
              invert_match: true
      transform:
        trace_statements:
          - context: span
            statements:
              - set(status.code, 1) where attributes["http.path"] == "/health"

              # after the http target has been anonymized, replace other aspects of the span
              - replace_match(attributes["http.route"], "/v1", attributes["http.target"]) where attributes["http.target"] != nil

              # replace the title of the span with the route to be more descriptive
              - replace_pattern(name, "/v1", attributes["http.route"]) where attributes["http.route"] != nil

              # set the route to equal the URL if it's nondescriptive (for the embedding case)
              - set(name, Concat([name, attributes["http.url"]], " ")) where name == "POST"
    service:
      extensions: [zpages, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, zipkin]
          processors: [tail_sampling, transform]
        metrics:
          receivers: [otlp]
          exporters: [debug]
          processors: [batch]
        logs:
          receivers: [otlp]
          exporters: [debug]
          processors: [batch]
podAnnotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: '8007'
podLabels: {}
podSecurityContext:
  fsGroup: 1000
# TODO: jdyer - uncomment this when microservice is added, currently no /health endpoint exists to check ...
# readinessProbe:
#   httpGet:
#     path: /health
#     port: http
replicaCount: 1
resources:
  limits:
    memory: 32Gi
    nvidia.com/gpu: 1
  requests:
    memory: 16Gi

securityContext: {}
service:
  port: 8000
  type: ClusterIP
  # string with space-delimited additional arguments to be passed to 'uvicorn'
  # in the service's main container
  nodePort: null

serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""

tolerations: []

# zipkin overrides
zipkinDeployed: false

imagePullSecrets:
  - name: gitlab-imagepull
  - name: nvcrimagepullsecret

# containerSecurityContext only affects the main container
containerSecurityContext: {}

ngcSecret:
  # If set to false, the chart expects a secret with name ngc-api to exist in the namespace
  # credentials are needed.
  create: false
  password: ""

imagePullSecret:
  create: false
  # Leave blank, if no imagePullSecret is needed.
  registry: "nvcr.io"
  name: "nvcrimagepullsecret"
  # If set to false, the chart expects either a imagePullSecret
  # with the name configured above to be present on the cluster or that no
  # credentials are needed.

  username: '$oauthtoken'
  password: ""

yoloxDeployed: true
yolox-nim:
  fullnameOverride: nv-ingest-yolox
  service:
    name: nv-ingest-yolox
    grpcPort: 8001
  nim:
    grpcPort: 8001

cachedDeployed: true
cached-nim:
  fullnameOverride: nv-ingest-cached
  service:
    name: nv-ingest-cached
    grpcPort: 8001
  nim:
    grpcPort: 8001

paddleocrDeployed: true
paddleocr-nim:
  fullnameOverride: nv-ingest-paddle
  service:
    name: nv-ingest-paddle
    grpcPort: 8001
  nim:
    grpcPort: 8001

deplotDeployed: true
deplot-nim:
  fullnameOverride: nv-ingest-deplot
  service:
    name: nv-ingest-deplot
    grpcPort: 8001
  nim:
    grpcPort: 8001

# Use this to load an image Pre NIM Factory via triton
triton:
  enabled: false

extraVolumeMounts: {}

